version: '3'
services:
  flask:
    networks:
      - app-network
      - webproxy
    environment:
      VIRTUAL_HOST: bitcoinacks.com
      LETSENCRYPT_HOST: bitcoinacks.com
      VIRTUAL_PORT: 5000
      PYTHONPATH: "/website/src/"
    ports:
      - "5000:5000"


networks:
  webproxy:
    external: true